# Generated by Django 5.2.4 on 2025-07-19 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appointment_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='division',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barishal', 'Barishal'), ('Sylhet', 'Sylhet'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], max_length=50),
        ),
        migrations.CreateModel(
            name='CustomAppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_date', models.DateField()),
                ('desired_timeslot', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('doctor_approved', 'Doctor Approved'), ('doctor_rejected', 'Doctor Rejected'), ('scheduled', 'Scheduled')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests_for_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
