# Generated by Django 5.2.4 on 2025-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_division_customappointmentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customappointmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_doctor', 'Pending Doctor'), ('doctor_approved', 'Doctor Approved'), ('doctor_rejected', 'Doctor Rejected'), ('scheduled', 'Scheduled')], default='pending', max_length=20),
        ),
    ]
